### ISSUE TITLE
Archlinux AUR package

### ISSUE THREAD

**Issue by grandchild** [dettus/d11amp#1]
Hi there, really cool project. This is not really an _issue_ more of a notification:

I took the liberty of packaging the player for Archlinux, I hope that's fine with you.
https://aur.archlinux.org/packages/d11amp

🙂

**Comment by dettus** [comment]
Awesome!
   
  
   Thank you so much!
   
  
    
   
  
   One thing though... may i ask that instead of the github tar.gz, you use my homepage's tar.bz2?
   
  
    
   
  
   Https://dettus.net/d11amp/d11amp_0.59.tar.bz2
   
  
    
   
  
   Thomas
   
   
   
    jakob ***@***.***> hat am 13.12.2022 14:48 CET geschrieben:
    
   
     
    
   
     
    
   
    Hi there, really cool project. This is not really an _issue_ more of a notification:
    
   
     
    
   
    I took the liberty of packaging the player for Archlinux, I hope that's fine with you.
    
   
    https://aur.archlinux.org/packages/d11amp
    
   
     
    
   
    🙂
    
   
     
    
   
    --
    
   
    Reply to this email directly or view it on GitHub:
    
   
    https://github.com/dettus/d11amp/issues/1

**Comment by dettus** [comment]
Oh, and feel free to include screenshots, the theme is EXPLICITLY licensed as CC-0. 
   
   
   
    jakob ***@***.***> hat am 13.12.2022 14:48 CET geschrieben:
    
   
     
    
   
     
    
   
    Hi there, really cool project. This is not really an _issue_ more of a notification:
    
   
     
    
   
    I took the liberty of packaging the player for Archlinux, I hope that's fine with you.
    
   
    https://aur.archlinux.org/packages/d11amp
    
   
     
    
   
    🙂
    
   
     
    
   
    --
    
   
    Reply to this email directly or view it on GitHub:
    
   
    https://github.com/dettus/d11amp/issues/1

**Comment by grandchild** [comment]
Sure, done. :)

**Comment by grandchild** [comment]
> Oh, and feel free to include screenshots, the theme is EXPLICITLY licensed as CC-0.

Packages don't usually have screenshots, so I'm not going to do that.

**Comment by hartwork** [comment]
@dettus the theme looks amazing, btw!

**Comment by dettus** [comment]
Yes! I think so too!

I will pass your email on to Christian. He will be very happy to read it. :)

Thomas

**Comment by ruesch** [comment]
> @dettus the theme looks amazing, btw!

I'm glad you like the theme. It was my first graphic artwork since my C64 and Amiga demoscene time and was really a lot of fun again. :-)
